### ISSUE TITLE
Project creation

### ISSUE THREAD

**Issue by larulirea** [CoEValencia/tutorial#1]
Once I had everything isntalled the tutorial sais to type "ng new tutorial" in a console, but which console? I could not find where should I type it. Then I found the option in the context menu "Open Devonfw CDM here" in tehe windows explorer and I could keep going.

Next step, "ng serve" didn't work either, then figured out that I had to go to the tutorial folder first.

**Comment by pajimene** [comment]
Thank you for your contribution. I've fixed it in the tutorial and the change is already published.
